name: node.js workflow

on: push

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v7

            - name: setup node.js
              uses: actions/setup-node@v7
              with: 
                 node-version: '14'

            - name: install dependencies
              run: npm install

            - name: start application
              run: npm start & npx wait-on http://127.0.0.1:8080

            - name: test application
              run: npm test 

            - name: build application
              run: npm run build

