name: node application

on:
  push:
    branches:
      - main

jobs:
    Build-node-application:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v7

            - name: install dependencies
              run: npm install
              
            - name: upload artifact
              uses: actions/upload-artifact@v7   
              with:
                name: node-application-artifact
                path: |
                    server.js
                    package.json
                    package-lock.json
                    public/